//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIDeffine.RecursosLocalizables {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringRecursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringRecursos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PIDeffine.RecursosLocalizables.StringRecursos", typeof(StringRecursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        internal static string Apellidos {
            get {
                return ResourceManager.GetString("Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿NECESITAS AYUDA?.
        /// </summary>
        internal static string Ayuda {
            get {
                return ResourceManager.GetString("Ayuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Camisetas.
        /// </summary>
        internal static string Camiseta {
            get {
                return ResourceManager.GetString("Camiseta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Colecciones.
        /// </summary>
        internal static string Colecciones {
            get {
                return ResourceManager.GetString("Colecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        internal static string ConfirmContra {
            get {
                return ResourceManager.GetString("ConfirmContra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacta con nosotros.
        /// </summary>
        internal static string Contacta {
            get {
                return ResourceManager.GetString("Contacta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string Contra {
            get {
                return ResourceManager.GetString("Contra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Has olvidado tu contraseña?.
        /// </summary>
        internal static string ContraOlvidada {
            get {
                return ResourceManager.GetString("ContraOlvidada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        internal static string Correo {
            get {
                return ResourceManager.GetString("Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Envíanos un correo electrónico.
        /// </summary>
        internal static string correoAyuda {
            get {
                return ResourceManager.GetString("correoAyuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No tienes cuenta?.
        /// </summary>
        internal static string Cuenta {
            get {
                return ResourceManager.GetString("Cuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DATOS DE ACCESO.
        /// </summary>
        internal static string Datos {
            get {
                return ResourceManager.GetString("Datos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DATOS PERSONALES.
        /// </summary>
        internal static string DatosPers {
            get {
                return ResourceManager.GetString("DatosPers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diseña tu estilo.
        /// </summary>
        internal static string Diseño {
            get {
                return ResourceManager.GetString("Diseño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar.
        /// </summary>
        internal static string Filtrar {
            get {
                return ResourceManager.GetString("Filtrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar Ropa.
        /// </summary>
        internal static string FiltrarRopa {
            get {
                return ResourceManager.GetString("FiltrarRopa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        internal static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        internal static string InicioSesion {
            get {
                return ResourceManager.GetString("InicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Máximo.
        /// </summary>
        internal static string Maximo {
            get {
                return ResourceManager.GetString("Maximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mínimo.
        /// </summary>
        internal static string Minimo {
            get {
                return ResourceManager.GetString("Minimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Teléfono +34 *********.
        /// </summary>
        internal static string numTelefono {
            get {
                return ResourceManager.GetString("numTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pantalones.
        /// </summary>
        internal static string Pantalones {
            get {
                return ResourceManager.GetString("Pantalones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio.
        /// </summary>
        internal static string Precio {
            get {
                return ResourceManager.GetString("Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regístrate.
        /// </summary>
        internal static string Registrarse {
            get {
                return ResourceManager.GetString("Registrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Talla.
        /// </summary>
        internal static string Talla {
            get {
                return ResourceManager.GetString("Talla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zapatillas.
        /// </summary>
        internal static string Zapatillas {
            get {
                return ResourceManager.GetString("Zapatillas", resourceCulture);
            }
        }
    }
}
